In [1]:
import numpy as np
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('final.csv')


In [3]:
df['Gender'] = df['Gender'].map({'Male' : 0,'M': 0,'F' : 1,'Female': 1})
df['Current Status'] = df['Current Status'].map({'Recovered': 1,'Deceased' : 0})

In [4]:
features = df[['Age Bracket','Gender']]
labels = df['Current Status']

In [5]:
train_features,test_features,train_labels,test_labels = train_test_split(features,labels,test_size  = 0.2)

In [6]:
scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

In [7]:
model = LogisticRegression()
model.fit(train_features,train_labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
print(model.score(train_features,train_labels))

0.8094059405940595


In [9]:
print(model.score(test_features,test_labels))

0.7920792079207921


In [10]:
print(model.coef_)

[[-1.33779713  0.02725836]]


In [11]:
College_Student = np.array([18,0])
Modi = np.array([67,1])
Trump = np.array([50,0])
Kid = np.array([4,0])

In [12]:
sample_patients = np.array([College_Student,Modi,Trump,Kid])
sample_patients = scaler.transform(sample_patients)

In [13]:
print(model.predict(sample_patients))

[1 1 1 1]


In [14]:
print(model.predict_proba(sample_patients))

[[0.03413486 0.96586514]
 [0.4904905  0.5095095 ]
 [0.24131079 0.75868921]
 [0.01333446 0.98666554]]
